name: sync-wiki

on:
  gollum:

env:
    GIT_AUTHOR_NAME: quarkusbot
    GIT_AUTHOR_EMAIL: quarkusbot@xam.dk

jobs:
    job-sync-wiki-to-docs:
        runs-on: ubuntu-latest
        if: github.event_name == 'gollum'
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.WIKI_PAT }} # allows us to push back to repo
                ref: master
            - name: Sync Wiki to Docs
              uses: newrelic/wiki-sync-action@master
              with:
                source: wiki
                destination: docs
                token: ${{ secrets.WIKI_PAT }}
                gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
                gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
                branch: master # since default branch is develop in this example